apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helper
  name: helper
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
    image: registry.fedoraproject.org/fedora-minimal
    name: helper
  restartPolicy: Never
